server:
  port: 8888

spring:
  application:
    name: config-service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      server:
        git:
          uri: file:///Users/mhyoo/Workspace/Spring_cloud/configuration
          default-label: master

management:
  endpoints:
    web:
      exposure:
        include: refresh,health,beans,httptrace,busrefresh